# Base image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install dependencies
RUN corepack enable && yarn install --production
RUN cd model && yarn install --production
RUN cd keeper && yarn install --production && yarn update && yarn build

# Start service
CMD [ "yarn", "start:keeper" ]
