database:
  name: movement_gaming_release
  host: momo-movement-production.cluster-caos3ssocrx6.us-west-1.rds.amazonaws.com
  port: 3306
  username:
    source: secret-manager
    value: movement-gaming-database-username-release
  password:
    source: secret-manager
    value: movement-gaming-database-password-release
  logging: false

redis:
  host: rize-referral-production.4mbrxl.ng.0001.usw1.cache.amazonaws.com
  port: 6379

secret-manager:
  region: us-west-1

aptos:
  clientUrl: https://aptos.testnet.suzuka.movementlabs.xyz/v1
  faucet: https://faucet.testnet.suzuka.movementlabs.xyz
  indexer: https://aptos.devnet.imola.movementlabs.xyz/indexer/v1/graphql
  network: testnet

core-contract:
  contractId: '0xd697cbe1d0ab95d9c79f847ee7a075db6e5d99196328785ff354fcbda7e28652'
  decimals: 6
  adminPrivateKey:
    source: use-value
    value: '0x96aed780a2db20ba5f02925617b0291591e888c61d99f76d9303339eff0683a8'

operator-list:
  - source: use-value
    value: '0x2afa331c7663b0ef5355ff9b1632ad249859c961c544d875573917adc12e4cac'
  - source: use-value
    value: '0xa97eb9fdb7d94837eec7da75f033e545df76399e73af95aa042939803f51c8fe'
  - source: use-value
    value: '0xe570232927e9aefad18ccdbf3c0d33933e0aea3f325bfd2a0744a86c63dc6a11'
  - source: use-value
    value: '0x042121d348658037466fe2df70976db40f0b3d4cdf9be0b0be08f542cca34e01'
  - source: use-value
    value: '0x09b7e21daa1910d49ad4fcbbbcee6b9ed1046b660d94b6f463fafc59ef17b63d'
  - source: use-value
    value: '0xcfc7cc5c31ca44427bfc4150602f23f235f5e45ef3be4947c429a3016c6d2e0e'
  - source: use-value
    value: '0xb7ad09b384a056b33ec3c9ff3ecf9a0ed77bec3887ea9498308dab6cdbe48d61'
  - source: use-value
    value: '0x0967947f5c0de35cc3fce8f6b297e23e60a321b1d81c85ba602c8c1cc1c9c88b'
  - source: use-value
    value: '0xb2d6acebef90e2142082954d19353724099950814c54cc2914f4127a040db617'
  - source: use-value
    value: '0xd0a3092eddea783d035463e767fd98163dd2573137a3224b9bfd430849ae36bd'

relayer:
  commandAccountRedisKey: 'momo-account-command-list'
  commandTokenRedisKey: 'momo-token-command-list'

monitoring:
  metricsNamespace: Movement-gaming
  region: us-west-1
  env: local
