database:
  name: movement_gaming_local
  host: 127.0.0.1
  port: 3306
  username:
    source: use-value
    value: movement
  password:
    source: use-value
    value: movement
  logging: false

redis:
  host: 127.0.0.1
  port: 6379

secret-manager:
  region: us-west-1

aptos:
  clientUrl: https://aptos.testnet.suzuka.movementlabs.xyz/v1
  faucet: https://faucet.testnet.suzuka.movementlabs.xyz
  indexer: https://aptos.devnet.imola.movementlabs.xyz/indexer/v1/graphql
  network: testnet

core-contract:
  contractId: '0xd697cbe1d0ab95d9c79f847ee7a075db6e5d99196328785ff354fcbda7e28652'
  decimals: 6
  adminPrivateKey:
    source: secret-manager
    value: momo-movement-admin-private-key

operator-list:
  - source: secret-manager
    value: momo-movement-operator-1
  - source: secret-manager
    value: momo-movement-operator-2
  - source: secret-manager
    value: momo-movement-operator-3
  - source: secret-manager
    value: momo-movement-operator-4
  - source: secret-manager
    value: momo-movement-operator-5
  - source: secret-manager
    value: momo-movement-operator-6
  - source: secret-manager
    value: momo-movement-operator-7
  - source: secret-manager
    value: momo-movement-operator-8
  - source: secret-manager
    value: momo-movement-operator-9
  - source: secret-manager
    value: momo-movement-operator-10

relayer:
  commandAccountRedisKey: 'momo-account-command-list'
  commandTokenRedisKey: 'momo-token-command-list'

monitoring:
  metricsNamespace: Movement-gaming
  region: us-west-1
  env: local
