[package]
name = 'momoMovement'
version = '0.0.1'

[addresses]
momo_movement = '0x32ad3ccd424c3c01e85ae52ccc8c439ceee2dadda294eee2e0c0a209fbde463a'
test_admin = '0xaa'
test_operator = '0xbb'
test_attacker = '0xcc'

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework/', rev = 'mainnet' }
