[package]
name = 'momoMovement'
version = '0.0.1'

[addresses]
momo_movement = '0x0ff15561341365ea41fe38bc19c357570d291abc03bf4b9adfba6ce6a05549d8'
test_admin = '0xaa'
test_attacker = '0xcc'

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework/', rev = 'mainnet' }
