[package]
name = 'momoMovement'
version = '0.0.1'

[addresses]
momo_movement = '0xd697cbe1d0ab95d9c79f847ee7a075db6e5d99196328785ff354fcbda7e28652'
test_admin = '0xaa'
test_operator = '0xbb'
test_attacker = '0xcc'

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework/', rev = 'mainnet' }
