database:
  name: movement_gaming_local
  host: 127.0.0.1
  port: 3306
  username:
    source: use-value
    value: movement
  password:
    source: use-value
    value: movement
  logging: false

redis:
  host: 127.0.0.1
  port: 6379

telegram:
  botToken: 6689153710:AAHVDcxHmD1LBZPYvpCbl-2d3kwBSZk6nh4

secret-manager:
  region: us-west-1

aptos:
  clientUrl: https://aptos.testnet.suzuka.movementlabs.xyz/v1
  network: testnet

core-contract:
  contractId: '0xd697cbe1d0ab95d9c79f847ee7a075db6e5d99196328785ff354fcbda7e28652'
  decimals: 6

relayer:
  commandAccountRedisKey: 'momo-account-command-list'
  commandTokenRedisKey: 'momo-token-command-list'

game:
  totalPlay: 10
  replenishmentInterval: 900 # 15 min
  coinsPerGame: 100
  timesPerGame: 3

invitation:
  codeLen: 6
  maxGenerateCodeTryTimes: 8
  target:
    0:
      level: 0
      memberNums: 1
      rewardCoins: 0
      rewardPlays: 0
    1:
      level: 1
      memberNums: 2
      rewardCoins: 300
      rewardPlays: 3
    2:
      level: 2
      memberNums: 3
      rewardCoins: 300
      rewardPlays: 3
    3:
      level: 3
      memberNums: 5
      rewardCoins: 300
      rewardPlays: 3
    4:
      level: 4
      memberNums: 7
      rewardCoins: 600
      rewardPlays: 3
    5:
      level: 5
      memberNums: 10
      rewardCoins: 600
      rewardPlays: 3
    6:
      level: 6
      memberNums: 13
      rewardCoins: 900
      rewardPlays: 3
    7:
      level: 7
      memberNums: 16
      rewardCoins: 900
      rewardPlays: 3
    8:
      level: 8
      memberNums: 20
      rewardCoins: 900
      rewardPlays: 5
    9:
      level: 9
      memberNums: 25
      rewardCoins: 1200
      rewardPlays: 5
    10:
      level: 10
      memberNums: 30
      rewardCoins: 1500
      rewardPlays: 5
    11:
      level: 11
      memberNums: 35
      rewardCoins: 1500
      rewardPlays: 5
  targetMemberNumsStep: 5
  targetRewardCoinsStep: 0
  targetRewardPlaysStep: 0

task:
  list:
    - taskId: 1
      taskName: Follow Rize Twitter
      taskLink: https://twitter.com/RIZE_Fi
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 2
      taskName: Join Rize Telegram Announcement
      taskLink: https://t.me/RIZE_Fi
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 3
      taskName: Join Rize Telegram Channel
      taskLink: https://t.me/RIZEFI_Official
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 4
      taskName: Check out Rize Galxe
      taskLink: https://app.galxe.com/
      rewardCoins: 300
      rewardPlays: 1

monitoring:
  metricsNamespace: Movement-gaming
  region: us-west-1
  env: local
