database:
  name: movement_gaming_local
  host: 127.0.0.1
  port: 3306
  username:
    source: use-value
    value: movement
  password:
    source: use-value
    value: movement
  logging: false

redis:
  host: 127.0.0.1
  port: 6379

telegram:
  botToken:
    source: secret-manager
    value: momo-movement-telegram-token

secret-manager:
  region: us-west-1

aptos:
  clientUrl: https://aptos.testnet.suzuka.movementlabs.xyz/v1
  network: testnet

core-contract:
  contractId: '0xd697cbe1d0ab95d9c79f847ee7a075db6e5d99196328785ff354fcbda7e28652'
  decimals: 6

relayer:
  commandAccountRedisKey: 'momo-account-command-list'
  commandTokenRedisKey: 'momo-token-command-list'

game:
  totalPlay: 10
  replenishmentInterval: 900 # 15 min
  coinsPerGame: 100
  timesPerGame: 3

invitation:
  codeLen: 6
  maxGenerateCodeTryTimes: 8
  target:
    0:
      level: 0
      memberNums: 1
      rewardCoins: 0
      rewardPlays: 0
    1:
      level: 1
      memberNums: 2
      rewardCoins: 3000
      rewardPlays: 3
    2:
      level: 2
      memberNums: 3
      rewardCoins: 3000
      rewardPlays: 3
    3:
      level: 3
      memberNums: 5
      rewardCoins: 3000
      rewardPlays: 3
    4:
      level: 4
      memberNums: 7
      rewardCoins: 6000
      rewardPlays: 3
    5:
      level: 5
      memberNums: 10
      rewardCoins: 6000
      rewardPlays: 3
    6:
      level: 6
      memberNums: 13
      rewardCoins: 9000
      rewardPlays: 3
    7:
      level: 7
      memberNums: 16
      rewardCoins: 9000
      rewardPlays: 3
    8:
      level: 8
      memberNums: 20
      rewardCoins: 9000
      rewardPlays: 5
    9:
      level: 9
      memberNums: 25
      rewardCoins: 12000
      rewardPlays: 5
    10:
      level: 10
      memberNums: 30
      rewardCoins: 15000
      rewardPlays: 5
    11:
      level: 11
      memberNums: 35
      rewardCoins: 15000
      rewardPlays: 5
  targetMemberNumsStep: 5
  targetRewardCoinsStep: 0
  targetRewardPlaysStep: 0

task:
  list:
    - taskId: 6
      taskName: Follow Momo Twitter
      taskLink: https://x.com/CultofMOMO
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 7
      taskName: Join Momo Discord
      taskLink: https://discord.gg/xCpW8BA3Ev
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 8
      taskName: Check out Momo Galxe
      taskLink: https://app.galxe.com/quest/momo
      rewardCoins: 300
      rewardPlays: 1
    - taskId: 5
      taskName: Bind Galxe
      taskLink: https://galxe.com/oauth?client_id=d6f2cbe50f818f64a14f0a1e7304b99d917a985845b4f2d11546d79ca735b3bc&scope=EVMAddress&redirect_uri=https://momo.rizefi.io/campaign/galxe_redirect
      rewardCoins: 300
      rewardPlays: 1

monitoring:
  metricsNamespace: Movement-gaming
  region: us-west-1
  env: local

campaign:
  referralCoins: 100

admin:
  authToken:
    source: use-value
    value: P@*v#aZKDFsd6XOxPx^A1r0t&wy#vucT

galxe:
  getAccessTokenUrl: https://api.galxe.com/oauth/auth/2/token
  getUserInfoUrl: https://api.galxe.com/oauth/api/2/user?scope=EVMAddress
  clientId:
    source: secret-manager
    value: galxe-momo-client-id
  clientSecret:
    source: secret-manager
    value: galxe-momo-client-secret
