database:
  name: movement_gaming_dev
  host: rize-referral-stage-database.cluster-caos3ssocrx6.us-west-1.rds.amazonaws.com
  port: 3306
  username:
    source: secret-manager
    value: movement-gaming-database-username-dev
  password:
    source: secret-manager
    value: movement-gaming-database-password-dev
  logging: false

redis:
  host: rize-referral-dev.4mbrxl.clustercfg.usw1.cache.amazonaws.com
  port: 6379

telegram:
  botToken: 7313665155:AAFMSop0BG-z7u-VTWDB4AFNaIlyIpEavI0

secret-manager:
  region: us-west-1

aptos:
  clientUrl: https://aptos.testnet.suzuka.movementlabs.xyz/v1
  network: testnet

core-contract:
  contractId: '0xe6578fbaccd4c937b27cb836a76a78c493d34310bdb214d95e8753ee06719f60'
  decimals: 6
  adminPrivateKey:
    source: use-value
    value: '0xc17ac4d7eea0e03774415f446c1cd8a93bdc6a63523dfa37a33c14c7d68dc5b1'

relayer:
  commandRedisKey: 'momo-command-list'

game:
  totalPlay: 20
  replenishmentInterval: 10 # 10 secs
  coinsPerGame: '10'

invitation:
  codeLen: 6
  maxGenerateCodeTryTimes: 8
  target:
    0:
      level: 0
      memberNums: 1
      rewardCoins: 0
      rewardPlays: 0
    1:
      level: 1
      memberNums: 9
      rewardCoins: 10
      rewardPlays: 1
    2:
      level: 2
      memberNums: 18
      rewardCoins: 20
      rewardPlays: 2
    3:
      level: 3
      memberNums: 27
      rewardCoins: 30
      rewardPlays: 3
  targetMemberNumsStep: 9
  targetRewardCoinsStep: 10
  targetRewardPlaysStep: 1

task:
  list:
    - taskId: 1
      taskName: Follow Rize Twitter
      taskLink: https://twitter.com/RIZE_Fi
      rewardCoins: 0
      rewardPlays: 1
    - taskId: 2
      taskName: Join Rize Telegram Announcement
      taskLink: https://t.me/RIZE_Fi
      rewardCoins: 0
      rewardPlays: 1
    - taskId: 3
      taskName: Join Rize Telegram Channel
      taskLink: https://t.me/RIZEFI_Official
      rewardCoins: 0
      rewardPlays: 1
    - taskId: 4
      taskName: Check out Rize Galxe
      taskLink: https://app.galxe.com/
      rewardCoins: 0
      rewardPlays: 1

monitoring:
  metricsNamespace: Movement-gaming
  region: us-west-1
  env: local
